"""add type and meta_data fields to rules

Revision ID: a52a3717a0f3
Revises: 8d3007e59e3c
Create Date: 2025-09-30 01:49:56.588411

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a52a3717a0f3"
down_revision: str | Sequence[str] | None = "8d3007e59e3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
