"""added is_official field for ruleset, plus rule sync

Revision ID: bb7f7c8a8df3
Revises: a52a3717a0f3
Create Date: 2025-10-01 20:04:24.890806

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bb7f7c8a8df3"
down_revision: str | Sequence[str] | None = "a52a3717a0f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rules", sa.Column("type", sa.String(length=50), nullable=True))
    op.add_column("rules", sa.Column("meta_data", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("rulesets", sa.Column("abbreviation", sa.String(length=20), nullable=True))
    op.add_column("rulesets", sa.Column("is_official", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rulesets", "is_official")
    op.drop_column("rulesets", "abbreviation")
    op.drop_column("rules", "meta_data")
    op.drop_column("rules", "type")
    # ### end Alembic commands ###
