"""
Cached navigation loader for rules content.

Loads navigation structure from pre-built JSON files (generated by
build_content_index management command) and caches them in memory.

This eliminates per-request file I/O for sidebar and prev/next navigation.
"""

import json
from functools import lru_cache
from pathlib import Path

from django.conf import settings

# Directory containing generated JSON files
DATA_DIR = Path(settings.BASE_DIR) / "static" / "data"


@lru_cache(maxsize=2)  # Cache both en and uk
def get_nav(lang: str) -> dict:
    """
    Load navigation structure (cached forever until restart).

    Returns:
        {
            "sections": {
                "combat": {
                    "title": "Combat",
                    "icon": "bi bi-shield",
                    "pages": [
                        {"slug": "combat-basics", "title": "Combat Basics"},
                        ...
                    ]
                },
                ...
            }
        }
    """
    nav_file = DATA_DIR / f"nav_{lang}.json"
    if nav_file.exists():
        with open(nav_file, encoding="utf-8") as f:
            return json.load(f)
    return {"sections": {}}


def get_section_pages(section: str, lang: str) -> list[dict]:
    """
    Get pages for a section from cached nav.

    Returns:
        [{"slug": "page-slug", "title": "Page Title"}, ...]
    """
    nav = get_nav(lang)
    return nav.get("sections", {}).get(section, {}).get("pages", [])


def get_section_info(section: str, lang: str) -> dict:
    """
    Get section metadata (title, icon) from cached nav.

    Returns:
        {"title": "Section Title", "icon": "bi bi-icon", "pages": [...]}
    """
    nav = get_nav(lang)
    return nav.get("sections", {}).get(section, {})


def get_all_sections(lang: str) -> dict:
    """
    Get all sections from cached nav.

    Returns:
        {"section_name": {"title": ..., "icon": ..., "pages": [...]}, ...}
    """
    nav = get_nav(lang)
    return nav.get("sections", {})


def clear_nav_cache():
    """
    Clear the navigation cache.

    Useful after rebuilding the index.
    """
    get_nav.cache_clear()
