"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env file if it exists (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-i#4)2aqhfm=p_1axpf-*ai8t*-qmc2+94)4m15j894a&1w@de9")

# Environment: "production" on Railway, "development" locally
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is off in production unless explicitly overridden
DEBUG = os.getenv("DEBUG", str(ENVIRONMENT != "production")).lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# Required for POST requests (htmx, CSRF) when behind a reverse proxy
# Railway: https://your-app.up.railway.app
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:8000").split(",")


# Application definition

INSTALLED_APPS = [
    # ServeStatic: use same static file handling in dev as production
    "servestatic.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "django_htmx",
    # Our apps
    "tools",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "servestatic.middleware.ServeStaticMiddleware",  # Async-compatible static file serving
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",  # Adds request.htmx for detecting htmx requests
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tools.context_processors.rules_nav",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Additional directories containing static files (besides app/static folders)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Directory where collectstatic copies files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# ServeStatic serves static files efficiently in production (async-compatible)
# Uses Brotli + gzip compression for smaller file sizes
STORAGES = {
    "staticfiles": {
        "BACKEND": "servestatic.storage.CompressedManifestStaticFilesStorage",
    },
}

# ServeStatic configuration
# https://archmonger.github.io/ServeStatic/latest/django-settings/
SERVESTATIC_MAX_AGE = 60 * 60 * 24 * 365 if not DEBUG else 0  # 1 year for production
SERVESTATIC_KEEP_ONLY_HASHED_FILES = True  # Save space: only store hashed versions

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# Security settings (production)
# Railway handles TLS termination, so we trust its HTTPS proxy
# =============================================================================
if not DEBUG:
    # Note: SECURE_SSL_REDIRECT is NOT set — Railway handles HTTPS redirection
    # at the proxy level. Setting it here breaks Railway's internal health checks
    # which use plain HTTP.
    SECURE_HSTS_SECONDS = 31536000  # W004: 1 year HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True  # W012: cookies only over HTTPS
    CSRF_COOKIE_SECURE = True  # W016: CSRF cookie only over HTTPS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # Trust Railway's proxy
