"""add unique constraints on slugs

Revision ID: 409125800384
Revises: bb7f7c8a8df3
Create Date: 2025-10-14 10:33:35.438161

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "409125800384"
down_revision: str | Sequence[str] | None = "bb7f7c8a8df3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_rule_ruleset_slug", "rules", ["ruleset_id", "slug"])
    op.create_unique_constraint(None, "rulesets", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rulesets", type_="unique")
    op.drop_constraint("uq_rule_ruleset_slug", "rules", type_="unique")
    # ### end Alembic commands ###
