"""added placeholder admin user

Revision ID: 8d3007e59e3c
Revises: 5449d2b942f6
Create Date: 2025-09-22 20:39:31.334481

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8d3007e59e3c"
down_revision: str | Sequence[str] | None = "5449d2b942f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
