# Generated by Django 6.0.1 on 2026-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypoSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(max_length=100)),
                ("page", models.CharField(max_length=100)),
                ("selected_text", models.TextField()),
                ("context", models.TextField(blank=True, help_text="Surrounding text for context (~50 chars)")),
                ("suggested_correction", models.TextField(blank=True)),
                ("page_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
